### ISSUE TITLE
error

### ISSUE THREAD

**Issue by upright2003** [keums/icassp2022-vocal-transcription#2]
Hello, I use colab. I could convert it before, but now I can’t use it at all. Can you correct the error?

Traceback (most recent call last):
  File "/content/icassp2022-vocal-transcription/src/singing_transcription.py", line 131, in <module>
    main(parser.parse_args())
  File "/content/icassp2022-vocal-transcription/src/singing_transcription.py", line 84, in main
    tempo = calc_tempo(path_audio)
  File "/content/icassp2022-vocal-transcription/src/quantization.py", line 26, in calc_tempo
    onset_strength = librosa.onset.onset_strength(y, sr=target_sr)
TypeError: onset_strength() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given

**Comment by upright2003** [comment]
I've asked chatgpt to resolve the issue:

/content/icassp2022-vocal-transcription/src/quantization.py

line 26
`onset_strength = librosa.onset.onset_strength(y=y, sr=target_sr)`
